# Generated by Django 5.2.8 on 2025-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='productName',
            field=models.CharField(),
        ),
    ]
